=== aws-iot-builder-tools/validation-tool-for-aws-iot-rules/validation/input-json-schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "sqlVersion": {
      "type": "string",
      "description": "SQL version needed for the test. Defaults to latest."
    },
    "topic": {
      "type": "string",
      "description":"This is the AWS IoT MQTT topic that the input payload will be published on. The same topic must be used in the Rule SQL FROM clause. "
    },
    "inputPayload": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        }
      ],
      "description":"This is the test input payload which will be published during the test execution. "
    },
    "inputSql": {
      "type": "string",
      "description":"This is the SQL statement of the IoT Rule under evaluation. "
    },
    "expectedOutput": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "object"
        },
        {
          "type": "array"
        }
      ]
    },
    "description":"This is the expected output that the input payload will be transformed into after scenario validation execution. "

  },
  "required": [
    "topic",
    "inputPayload",
    "inputSql",
    "expectedOutput"
  ]
}

=== aws-iot-builder-tools/validation-tool-for-aws-iot-rules/validation/validation-data/undefined-function-check-payload.json
{
  "sqlVersion": "2016-03-23",
  "topic": "test/test6",
  "inputPayload": {
    "state": {
      "command": "DOOR_OPEN",
      "debug": "FALSE"
    },
    "version": "3.1"
  },
  "inputSql": "SELECT state.debug AS state.debug, state.command AS state.command, version FROM 'test/test6' WHERE IsUndefined(state.debug) = False OR IsUndefined(state.command) = False",
  "expectedOutput": {
    "state": {
      "debug": "FALSE",
      "command": "DOOR_OPEN"
    },
    "version": "3.1"
  }
}

=== aws-iot-builder-tools/validation-tool-for-aws-iot-rules/validation/validation-data/casting-sensor-payload.json
{
  "sqlVersion": "2016-03-23",
  "topic": "test/test4",
  "inputPayload": "{\"temperature\":23.07,\"humidity\":49.9397,\"light\":5.0}",
  "inputSql": "SELECT temperature, humidity, cast(light as double) as newLight FROM 'test/test4'",
  "expectedOutput": "{\"temperature\":23.07,\"humidity\":49.9397,\"newLight\":5}"
}

=== aws-iot-builder-tools/validation-tool-for-aws-iot-rules/validation/validation-data/payload-enrichment-with-functions.json
{
  "sqlVersion": "2016-03-23",
  "topic": "123/ACT_123/slider/req",
  "inputPayload": { "values": [50, 100]},
  "inputSql": "SELECT *, topic(1) as deviceId, topic(2) as actuatorId, topic(3) as cmd FROM '+/+/+/req'",
  "expectedOutput":{ "values": [50, 100], "deviceId": "123","actuatorId": "ACT_123", "cmd": "slider"  }
}

=== aws-iot-builder-tools/validation-tool-for-aws-iot-rules/validation/validation-data/filter-out-from-input-payload.json
{  "sqlVersion": "2016-03-23",
  "topic": "test/test3",
  "inputPayload": {
    "Pos": [
      {
        "L1": 36.903999599999999,
        "L2": -25.263283700000002,
        "S": 5
      },
      {
        "L1": 36.903999599999977,
        "L2": -25.2632837000000772,
        "S": 6
      },
      {
        "L2": -25.263283700000002,
        "S": 7
      }
    ]
  },
  "inputSql": "SELECT (SELECT * FROM Pos WHERE L1 <> isNull(SELECT VALUE L1 FROM Pos) ) as required_array FROM 'test/test3'",
  "expectedOutput": {
    "required_array": [
      {
        "L1": 36.9039996,
        "L2": -25.263283700000002,
        "S": 5
      },
      {
        "L1": 36.90399959999998,
        "L2": -25.263283700000077,
        "S": 6
      }
    ]
  }
}
